tap "lightpanda-io/browser"
tap "zdk/tools"

brew "mas"
brew "awscli"
brew "colima"
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "fzf"
brew "gh"
brew "jq"
cask "1password-cli"
brew "libpq"
brew "lightpanda-io/browser/lightpanda"
brew "lowfat"
brew "node"
brew "peon-ping"
brew "pulumi"
brew "python@3.13"
brew "terraform"
brew "tmux"
brew "zoxide"

cask "flameshot"
cask "session-manager-plugin"

mas "Amphetamine", id: 937984704
